#!/bin/bash

#-----DECLARATIONS------#

dir="$(dirname "$0")"

EMACS="$dir/data/build_emacs_24.sh"

# CUSTOMIZATION
function customize {
echo ''
show_info 'What would you like to do? '
echo ''
echo '1. Configure system?'
echo '2. Compile and install emacs 24.4?'
echo 'r. Return'
echo ''
show_info 'Enter your choice :' && read REPLY
case $REPLY in
1) 
	clear && config;; # System Configuration
# Install emacs 24.4	
2)
	echo 'Compile emacs 24.4...'
	echo ''
	show_info 'Requires Root privileges...'
	sudo bash $EMACS
	show_success 'Done.'
	customize
	;;	
# Return	
	[Rr]*) clear && main;; # Return
	* ) clear && show_error '\aNot an option, try again.' && customize;; # Invalid choice
esac
}
