#!/bin/sh

#----- DECLARATIONS -----#

dir="$(dirname "$0")"

GEXTRAS="$dir/data/gnome-extras.list"

# INSTALL GNOME COMPONENTS
function gnome {
echo ''
echo '1. Add GNOME3 PPA?'
echo '2. Add GNOME3 Staging PPA?'
echo 'r. Return.'
echo ''
read -p 'What would you like to do? (Enter your choice) : ' REPLY
case $REPLY in
# Add GNOME3 PPA
1)
# Add repository
	echo 'Adding GNOME3 PPA to software sources...'
	show_info 'Requires root privileges:'
	sudo add-apt-repository -y ppa:gnome3-team/gnome3
# Update repository information
	echo 'Updating repository information...'
	sudo apt-get update
	show_success 'Done.'
# Upgrade system?
	read -p 'Perform system upgrade? (Y)es, (N)o : ' REPLY
	case $REPLY in
# Positive action
[Yy]* )
	show_info 'Requires root privileges:'
	sudo apt-get dist-upgrade -y
	show_success 'Done.'
	gnome
	;;
# Negative action
[Nn]* )
	clear && gnome
	show_success 'Done.'
	;;
# Error
* )
	clear && show_error '\aSorry, try again.'
	gnome
	;;
esac
;;
# Add GNOME3 Staging PPA
2)
# Add repository
	echo 'Adding GNOME3 Staging PPA to software sources...'
	show_info 'Requires root privileges:'
	sudo add-apt-repository -y ppa:gnome3-team/gnome3-staging
# Update repository information
	echo 'Updating repository information...'
	sudo apt-get update
	show_success 'Done.'
	echo ''
# Upgrade system?
	read -p 'Perform system upgrade? (Y)es, (N)o : ' REPLY
	case $REPLY in
# Positive action
[Yy]* )
	show_info 'Requires root privileges:'
	sudo apt-get dist-upgrade -y
	show_success 'Done.'
	gnome
	;;
# Negative action
[Nn]* )
	clear && gnome
	show_success 'Done.'
	;;
# Error
* )
	clear && show_error '\aSorry, try again.'
	gnome
	;;
esac
;;
# Return
[Rr]*)
clear && main;;
# Invalid choice
* )
clear && show_error '\aNot an option, try again.' && gnome;;
esac
}
