#!/bin/sh

#----- DECLARATIONS -----#

dir="$(dirname "$0")"

SECURITY="$dir/data/sec_tools.list"

# INSTALL APPLICATIONS
function security {
# Install Favourite Applications
echo ''
echo 'Installing selected security tools...'
echo ''
echo 'Current package list:'
echo ''
for package in $(cat $SECURITY)
do
echo -e '\t'$package
done
echo ''
show_info 'Proceed? (Y)es, (N)o : ' && read REPLY
echo ''
case $REPLY in
# Positive action
[Yy]* )
	show_info 'Requires root privileges:'
# Feel free to change the contents of 'sec_tools.list' to whatever suits your preferences.
	sudo apt-get install -y --no-install-recommends $(cat $SECURITY)
	show_success 'Done.'
	main
	;;
# Negative action
[Nn]* )
	clear && main
	;;
# Error
* )
	clear && show_error '\aSorry, try again.'
	security
	;;
esac
}
