#!/bin/sh

#----- DECLARATIONS -----#

dir="$(dirname "$0")"

VBOX="$dir/data/vbox_install"

# THIRD PARTY APPLICATIONS

function thirdparty {
echo ''
show_info 'What would you like to install? '
echo ''
echo '1. Google Talk Plugin?'
echo '2. Steam?'
echo '3. Inkscape Stable?'
echo '4. Oracle VirtualBox?'
echo '5. Dropbox?'
echo '6. Insync?'
echo 'r. Return'
echo ''
show_info 'Enter your choice:' && read REPLY
case $REPLY in
# Google Talk Plugin
1)
	echo 'Downloading Google Talk Plugin...'
# Download Debian file that matches system architecture
	case `uname -i` in
	i386|i486|i586|i686)
		wget https://dl.google.com/linux/direct/google-talkplugin_current_i386.deb
	;;
	x86_64)
	wget https://dl.google.com/linux/direct/google-talkplugin_current_amd64.deb
	;;
	*)
	show_error "Couldn't find a download that matches your system." && thirdparty
	;;
esac
# Install package(s)
	echo 'Installing Google Talk Plugin...'
	echo 'Requires root privileges:'
	sudo dpkg -i google-talkplugin_current*.deb
	sudo apt-get install -fy
# Cleanup and finish
	rm google-talkplugin_current*.deb
	show_success 'Done.'
	thirdparty
	;;
# Steam
2)
	echo 'Downloading Steam...'
# Download Debian file that matches system architecture
	case `uname -i` in
		i386|i486|i586|i686)
		wget http://repo.steampowered.com/steam/archive/precise/steam_latest.deb
	;;
	x86_64)
		wget http://repo.steampowered.com/steam/archive/precise/steam_latest.deb
	;;
	*)
		show_error "Couldn't find a download that matches your system." && thirdparty
	;;
esac
# Install package(s)
	echo 'Installing Steam...'
	echo 'Requires root privileges:'
	sudo dpkg -i steam*.deb
	sudo apt-get install -fy
	echo 'Installing Steam dependencies...'
	echo 'Requires root privileges:'
	sudo apt-get install -y libgl1-mesa-glx libgl1-mesa-dev libgl1-mesa-dri:i386 libgl1-mesa-glx:i386 libc6:i386
# Cleanup and finish
	rm steam*.deb
	show_success 'Done.'
	thirdparty
	;;
# Inkscape Stable
3)
# Add repository
	echo 'Adding Inkscape Stable PPA to software sources...'
	show_info 'Requires root privileges:'
	sudo add-apt-repository ppa:inkscape.dev/stable
# Update repository information
	echo 'Updating repository information...'
	sudo apt-get update
# Install
	echo 'Installing Inkscape Stable...'
	sudo apt-get install --only-upgrade -y inkscape
	show_success 'Done.'
	thirdparty
	;;
# Oracle VirtualBox
4)
	echo 'I will now add Virtualbox repo to sources.list and install Virtualbox...'
	show_info 'Requires root privileges:'
	sudo bash $VBOX
	show_success 'Done.'
	thirdparty
	;;
# Dropbox
5)
	echo 'Downloading Dropbox...'
# Download Debian file that matches system architecture
	case `uname -i` in
	i386|i486|i586|i686)
	wget https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.02.12_i386.deb
	;;
	x86_64)
	wget https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.02.12_amd64.deb
	;;
	*)
	show_error "Couldn't find a download that matches your system." && thirdparty
	;;
esac
# Install package(s)
	echo 'Installing Dropbox...'
	echo 'Requires root privileges:'
	sudo dpkg -i dropbox_*.deb
	sudo apt-get install -fy
# Cleanup and finish
	rm dropbox_*.deb
	show_success 'Done.'
	thirdparty
	;;
# Insync
6)
	echo 'Downloading Insync...'
# Download Debian file that matches system architecture
	case `uname -i` in
	i386|i486|i586|i686)
	wget http://s.insynchq.com/builds/insync_1.2.3.35090-trusty_i386.deb
	;;
	x86_64)
	wget http://s.insynchq.com/builds/insync_1.2.3.35090-trusty_amd64.deb
	;;
	*)
	show_error "Couldn't find a download that matches your system." && thirdparty
	;;
esac
# Install package(s)
	echo 'Installing Insync...'
	echo 'Requires root privileges:'
	sudo dpkg -i insync_*.deb
	sudo apt-get install -fy
# Cleanup and finish
	rm insync_*.deb
	show_success 'Done.'
	thirdparty
	;;
#
# Return
[Rr]*)
	clear && main;;
# Invalid choice
* )
	clear && show_error '\aNot an option, try again.' && thirdparty;;
esac
}
